### ISSUE TITLE
do rendered versions of each PR get posted back to the  PR?

### ISSUE THREAD

**Issue by ctb** [greenelab/meta-review#121] opened 2019-02-05 18:00 UTC
I assume this happens but want to double check (and am at the far end of a lousy Internet connection right now). So this is really more of an "@ctb todo" item.

**Comment by agitter** [comment] 2019-02-05 19:03
This is a good idea.  It could be directly linked, but currently is not.

Currently, the `gh-pages` commit cross-references the PR so that commit is linked in the PR.  From that commit message, the commit hash can be used to get to the versioned permalink of the manuscript.  It would be better to directly provide that URL in the commit message.

To be more explicit, this is what the commit message contains:
![image](https://user-images.githubusercontent.com/3532898/52297368-31b66f80-2946-11e9-9db0-7c71301d9495.png)

We could add the permalink https://greenelab.github.io/meta-review/v/e3a3e7ab663491ee6e4b1e8363c771b274ed0fe3/

**Comment by dhimmel** [comment] 2019-02-05 19:17
@agitter I think @ctb question "do rendered versions of each PR get posted back to the PR" refers to whether the output files from a PR build are posted in a PR comment. Currently, the answer is no.

If a PR is merged, the commit message links shown by @agitter do show up in the PR's timeline. However, prior to being merged, the only way to see the output PDF or HTML is to build it locally.

It would be helpful to gain access to output files from PR builds. One issue with uploading them to GitHub is that PR builds cannot have any secrets, which makes things like authentication to upload to GitHub difficult. I will look into [Travis artifacts upload](https://docs.travis-ci.com/user/uploading-artifacts/), but the issue is that due to PRs being from untrusted sources:

> the artifacts addon is not available for pull request builds.

Perhaps we can find (or make) a temporary PDF or Manubot HTML hosting service that doesn't require authentication.

**Comment by agitter** [comment] 2019-02-06 15:37
Thanks for explaining @dhimmel, that makes sense.  This would be a really great feature, especially for PR reviewers to quickly check whether new references were extracted correctly.

> Perhaps we can find (or make) a temporary PDF or Manubot HTML hosting service that doesn't require authentication.

If we stick with Travis, that may be the only solution.  https://github.com/travis-ci/travis-ci/issues/5579 gives a good overview of the issue and current status.  Per the latest comments, CircleCI and AppVeyor do support artifacts.

**Comment by agitter** [comment] 2019-03-22 19:17
Because Travis CI doesn't directly support this, I propose we open an issue at `manubot/rootstock` to continue our planning and add it as an area of future work in #133.  This really is an important feature that I would like to pursue.

**Closed as completed** 2019-03-25 13:40 UTC
