### ISSUE TITLE
General "gestalt" screenshot of Manubot

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/meta-review#181] opened 2019-03-26 13:48 UTC
Perhaps it would be good to have another screenshot that shows Manubot as a whole – Something that shows in one picture the basic idea of Manubot and what it can do. 

The plugin screenshots are good, but they are purposefully narrow-view as to only focus on the particular feature they're highlighting. We'll need something like this for the manubot.org landing page and other related "marketing" pages/media eventually. Maybe a screenshot that includes the tooltips, accordion, an image, an equation, a table, and some links. And then maybe even a command prompt off to the side, or a folder view of the directories.

**Comment by dhimmel** [comment] 2019-03-26 14:12
I agree a single shot that can provide a big picture view of Manubot would be valuable. If gestalt, I would probably be in favor of including it in this manuscript. But even if not, we'll definitely have a use for it.

**Comment by agitter** [comment] 2019-03-26 14:45
Great idea.  A big picture graphic for the Manubot front end would be valuable.

To truly be a "gestalt" figure, it may need to include the front end + the continuous deployment back end.  Keeping the scope to the front end for now would make sense though, especially for our short term branding and resubmission efforts for this manuscript.

**Comment by dhimmel** [comment] 2019-04-04 14:32
@vincerubinetti given our resubmission timeline, if you'd like this figure to be in the manuscript, we'd probably need it by Friday.

**Comment by dhimmel** [comment] 2019-04-09 13:26
Looks like this is not going to make it into the manuscript due to the deadline. Hence, I'll close it. But if the issue is relevant elsewhere (like for the eventual manubot.org landing page), we can reopen / transfer this issue.

**Closed as completed by dhimmel** 2019-04-09 13:26 UTC
