### ISSUE TITLE
Reviewer 2 comment 10

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#139] opened 2019-02-08 12:46 UTC
> In the discussion, to what extent a contributor can only use the GitHub interface (text editor + automated PR)? Would not that be a way to lower the technical entry level for contributors?

**Comment by slochower** [comment] 2019-02-10 17:44
This could be addressed by the clunky figure proprosed in #130.

**Comment by agitter** [comment] 2019-02-12 20:15
We could also consider a short video showing this process.

**Comment by slochower** [comment] 2019-02-13 02:27
Here's a really inelegant "sketch"  of what it could look like.
![manubot](https://user-images.githubusercontent.com/5393995/52682303-c8a99b80-2ef3-11e9-8558-719c08a7070d.gif)

**Comment by agitter** [comment] 2019-02-13 15:12
@slochower That's awesome.  I think this would go a long way for making the whole process more clear and attracting users.

This participant-centric view is very important.  Is it more streamlined if we avoid switching to the participant's fork?  I believe that a new participant can edit a file in the original repository (e.g. greenelab/meta-review) and then create a branch and pull request without switching to their fork.  I need to experiment with this again.

We could also have a maintainer-centric video that shows this pull request coming in.  The maintainer could review and propose a suggestion (maybe adding a citation).  The participant adds the citation to their pull request, the maintainer approves and merges, and we close with a shot of the updated manuscript.

**Comment by dhimmel** [comment] 2019-02-13 15:21
> I believe that a new participant can edit a file in the original repository (e.g. greenelab/meta-review) and then create a branch and pull request without switching to their fork.

Yes, we should use the method where you click on the pencil icon in the upstream manuscript, then GitHub creates the fork for you (if necessary), adds your commit to a new branch (e.g. `patch-1`), and then sends you to an open PR page. We want to make sure we don't encourage forks to commit to their master branch as the current recording shows.

This is the [workflow](https://slides.com/dhimmel/psb#/8/7 "remember to use arrows to navigate through slide") we used for the [psb-manuscript](https://github.com/dhimmel/psb-manuscript). You can also show then going to the pull request and editing a second file (for PRs that need edits in multiple files, since the GH interface can only do one file per commit).

**Comment by agitter** [comment] 2019-02-13 15:34
> You can also show then going to the pull request and editing a second file

This might be something that is better stated or written instead of showing it in the interest of keeping the video short, especially if we show the maintainer side as well.

**Comment by slochower** [comment] 2019-02-13 15:48
Yep.  I can take another crack later. But FYI, I skipped creating a branch on my form because the video file size was getting too big for GitHub to upload in an issue.

**Comment by dhimmel** [comment] 2019-02-13 15:50
> the video file size was getting too big for GitHub to upload in an issue.

What software are you using to create the GIF? We probably want a mp4 version as well, perhaps on YouTube, and then we can just use the GIFs places that don't support YouTube embeds.

**Comment by slochower** [comment] 2019-02-13 16:38
Simplescreenrecorder to MKV; ffmpeg to GIF. 

Would be nice to do the other side: Mainers could request a citation, for example, but then I’d have to actually make a demo PR. Would that be okay? Anyone know if it’s acceptable with Github’s TOS to make dummy accounts?

**Comment by agitter** [comment] 2019-03-22 18:48
@slochower I really liked this video.  Will you be able to update it or is it difficult to do while traveling?  If you have the ability to update, I can discuss details of the workflow with you and @dhimmel.

Once we establish the demo manuscript in #155 we could use that to actually make a PR.

**Comment by slochower** [comment] 2019-03-22 20:09
I can update it. I think I was waiting to figure out if I could/should make an actual PR on the main repository. But I think using the "try me" repository is a great solution! I'll keep me eye on that and redo this video. Should I add an example citation too?

**Comment by agitter** [comment] 2019-03-22 21:35
> Should I add an example citation too?

Yes, I think that would be a great use case and let readers see the cite by id feature.  We could draft a workflow between a Participant (P) and Maintainer (M) before the try-me repo is ready.  How about:

P: Uses the pencil icon edit (per above) to add a sentence using a new branch
M: Reviews and requests a supporting reference
P: Adds the reference
M: Approves and merges

Is that too long?  We would need some editing to show that well and smooth the transitions.  One of us may also need to be dropped from the @manubot organization temporarily in order to show the default pencil edit options.  Otherwise the branch will get created on `manubot/try-me` instead of a `participant/try-me` fork.

**Comment by slochower** [comment] 2019-03-22 22:45
I'll give this a shot and see if we can keep the whole thing under a minute. 

Do you think we'll embed the video in the manuscript? It might also work well in a README.

**Comment by agitter** [comment] 2019-03-23 11:43
@dhimmel suggested 
> We probably want a mp4 version as well, perhaps on YouTube, and then we can just use the GIFs places that don't support YouTube embeds.

I'm not sure whether we can embed a video in the manuscript.  We could for the HTML Manubot output, but I don't know how we could adapt it for PLOS.  Maybe we have to link to an external video?

If you need me to act as the participant or maintainer for the video, we could coordinate the PR.

**Comment by slochower** [comment] 2019-03-25 18:16
@agitter I can carve out some time later this afternoon. Do you think we'll have the `try-me`/`playground` manuscript up today?

**Comment by dhimmel** [comment] 2019-03-25 18:18
I can set up the manuscript whenever... just waiting till we finalize a name.

**Comment by slochower** [comment] 2019-03-25 18:20
@dhimmel Would you mind dropping a note here and tag me when you setup the manuscript?

**Comment by slochower** [comment] 2019-03-27 15:53
I see https://github.com/manubot/try-manubot is up now.

@agitter how about we follow the plan you suggested above.

0. We show the rendered manuscript.
1. I make a PR.
2. You request a citation.
3. I add the citation.
4. You approve the PR.
5. We show the rendered manuscript.

The question is how to integrate these into a coherent movie. If you record steps 2 and 4, we might be able to just stitch them all together, but I'm not sure if the different browser window sizes and resolutions will mess things up. I will give steps 0-1 a try later tonight and post it here for you to see.

**Comment by slochower** [comment] 2019-03-28 04:02
Here's a rough cut. I tried to not go too fast to obscure what I was doing, but it's already 1 minute 20 seconds.

![Manubot](https://user-images.githubusercontent.com/5393995/55129244-c048a100-50ec-11e9-9efd-1f039424f947.gif)

**Comment by agitter** [comment] 2019-03-28 13:09
@slochower I had commented in `https://github.com/manubot/try-manubot/pull/2` but did not realize at first that was the PR for this video.  I'll make a more deliberate and carefully worded review later.

I like your workflow above.  To speed things up, we could only show the contributor's perspective (i.e. yours) and not record my side.  You would come back to the PR, look at the new review, and make that change in the browser.  Later, you could come back again after I had approved to show what that looks like and then proceed to step 5.  Or maybe after I approve an merge?

Showing your side only would also help us resolve this faster.  I haven't done screen capture recently and would need some time to set it up.

**Comment by agitter** [comment] 2019-03-28 15:24
@slochower I reviewed the video now and think this is perfect.  I like that your initial view of the manuscript only shows the abstract because the main text is currently empty.

@dhimmel do you have any comments?

If we like this for the first part of the video, then I will proceed to review the pull request.  I will comment on the edited line saying `Please add a URL citation to this manuscript.` and request changes.

**Comment by slochower** [comment] 2019-03-28 15:38
> I like that your initial view of the manuscript only shows the abstract because the main text is currently empty.

Right :)

> I will comment on the edited line saying Please add a URL citation to this manuscript. and request changes.

Okay great!

**Comment by dhimmel** [comment] 2019-03-28 16:34
The recording is good.

> If we like this for the first part of the video, then I will proceed to review the pull request. I will comment on the edited line saying Please add a URL citation to this manuscript. and request changes.

Are you also going to request the authorship information to `metadata.yaml`? I think it could be useful to show how you can edit additional files using the GitHub UI in a PR. However, it could also be a bit too in the weeds.

**Comment by agitter** [comment] 2019-03-28 16:50
> Are you also going to request the authorship information to metadata.yaml?

I wasn't planning to but I'm open to suggestions.  I didn't realize this was possible until you mentioned it.  Is the easiest route to browse the repo on that branch (https://github.com/slochower/try-manubot/tree/patch-1) and then pencil edit another file?

I'm inclined to keep this demo simple and include in our documentation somewhere that this is possible.

**Comment by dhimmel** [comment] 2019-03-28 18:52
> I didn't realize this was possible until you mentioned it. Is the easiest route to browse the repo on that branch (https://github.com/slochower/try-manubot/tree/patch-1) and then pencil edit another file?

Yeah. You can get to the branch from the PR page, by the link in the sentence:

> Add more commits by pushing to the **patch-1** branch on slochower/try-manubot.

Or you can click the pencil on the PR, and then click through the filepath up top to change files.

Note that as a PR reviewer, we can always provide the author with a direct link to edit the file on the right branch like:

```
https://github.com/slochower/try-manubot/edit/patch-1/content/metadata.yaml
```

**Comment by agitter** [comment] 2019-03-28 19:49
@slochower I submitted my `try-manubot` review so you can proceed with step 3 whenever you're ready.

**Comment by slochower** [comment] 2019-03-28 19:49
@agitter Got your PR comment, thanks! Which citation should I use? 

`@url:https://greenelab.github.io/meta-review/`?

(Do we have another choice at the moment?)

**Comment by agitter** [comment] 2019-03-28 19:52
@slochower yes, let's use that one wrapped in square brackets:

`[@url:https://greenelab.github.io/meta-review/]`

**Comment by agitter** [comment] 2019-03-28 22:04
@slochower after you make this change and I approve, I suggest that in step 5 you do something like:

5a: Click the green check by the commit hash to show that the build passed
5b: Move your cursor to the approval message to indicate that it was re-reviewed, approved, and merged
5c: Switch to the updated rendered manuscript

**Comment by slochower** [comment] 2019-03-29 01:07
How's this look for step 3?

![Manubot 2](https://user-images.githubusercontent.com/5393995/55202339-6522b700-519d-11e9-9a02-b5a13b5ba8e0.gif)

**Comment by agitter** [comment] 2019-03-29 11:22
The step 3 video looks good to me.  Using the `patch-1` link to do the next pencil edit is a good workflow to showcase because it will teach users how to edit new files if needed.  It is slightly faster to instead do the next pencil edit from the `Files changed` tab of the pull request, but I'm happy to use this more general approach.

@slochower shall I approve and squash merge this pull request?

**Comment by slochower** [comment] 2019-03-29 11:33
Yes I think so. Will try to step 5 in a few hours.

**Comment by agitter** [comment] 2019-03-29 11:51
Okay, I merged.  If you show the new reference in the updated rendered manuscript, I recommend using the citation tooltip instead of clicking it.  In general, showing both the tooltip and reference list would be ideal, but the references look strange without a manuscript body.

**Comment by slochower** [comment] 2019-03-29 18:44
How's this for step 5? Too clunky? I can redo.
![Manubot 5](https://user-images.githubusercontent.com/5393995/55255464-1888bb80-5231-11e9-9839-3cfcebbc834c.gif)

**Comment by agitter** [comment] 2019-03-30 12:05
I think this looks good.  @dhimmel what do you think?

Is there an easy way to add transitions with titles between the three segments?  The transitions will be very abrupt if we directly stitch these all together.

**Comment by slochower** [comment] 2019-03-30 12:06
I can try to add transition titles but won’t get a chance to look into it until early next week.

**Comment by slochower** [comment] 2019-03-31 21:24
@agitter, @dhimmel: thoughts? https://drive.google.com/open?id=1FbHhpoYhnkfXqeIOHQ86yyY3_9k5SFQF

**Comment by agitter** [comment] 2019-04-01 15:07
I like how it came together.  The three transition titles could each be a couple seconds longer.  I have no other major suggestions.

It feels self-explanatory to me without a voiceover or more text annotations describing the process.  However, I already know the workflow.  Should we ask a few volunteers who are unfamiliar with Manubot to give feedback?

Do we plan to host this on YouTube and link it from the manuscript (and rootstock)?

**Comment by slochower** [comment] 2019-04-01 15:28
> I like how it came together. The three transition titles could each be a couple seconds longer. I have no other major suggestions.

I can do this; I also think one has a period and the other does not.

> It feels self-explanatory to me without a voiceover or more text annotations describing the process. However, I already know the workflow. Should we ask a few volunteers who are unfamiliar with Manubot to give feedback?

Yes, good idea. Anyone you know? Most of my group is at the ACS meeting in Orlando right now...

> Do we plan to host this on YouTube and link it from the manuscript (and rootstock)?

Right, good question. YouTube is fine with me. I think there are also some other open source alternatives. I'm happy to put it under my name (I think I need to create an account) or we could create a Manubot account (if so, we might want to create a Manubot email address).

**Comment by agitter** [comment] 2019-04-01 15:47
> Yes, good idea. Anyone you know? Most of my group is at the ACS meeting in Orlando right now...

I'll ask my group to do look at it.

I'll let you and @dhimmel resolve where and how to host the video.  I'm open to anything.

**Comment by dhimmel** [comment] 2019-04-01 17:22
> if so, we might want to create a Manubot email address

Currently, we have `contact@manubot.org` will forward to me, so we can use it when an email is needed.

We could post the video on YouTube or Figshare ([example](https://doi.org/10.17637/rh.5987851.v1)), which also allows embeds. Any other recommendations anyone?

Did we want to include the video in the manuscript? We could use the HTML embed code or [pandoc-videofilter](https://github.com/unmanbearpig/pandoc-videofilter). The preview would currently fail when exporting to PDF, since WeasyPrint doesn't support javascript. It also would probably cause trouble when resubmitting to PLOS Comp Bio. We could submit it as a [supplemental file](https://journals.plos.org/ploscompbiol/s/supporting-information)? CC @vincerubinetti

**Comment by agitter** [comment] 2019-04-01 18:03
@dhimmel I'm open to including it in the manuscript and also making it available externally.  A nice feature of Figshare is that we can version and update it.  I don't know how YouTube handles updates.

@slochower my group members think the video is good overall and had the following specific comments:
- accelerating the typing scenes would help reduce the time and keep viewer attention
- a voiceover would be helpful to explain what is going on and make sure that the main Manubot features we're highlighting - the fact that anyone can make such a PR, the ease of adding a citation, the automated build, documenting each contribution and review - are obvious
- (my aside, we could also use text captions to highlight these same features in relevant parts of the video if that is more practical to prepare)
- they also shared this example of a GitHub tutorial with a decent voiceover https://www.youtube.com/watch?v=XdhuWDdu-rk

Our choice of video hosting site may influence how we proceed.  We're trying to resubmit ASAP, and I like this version.  If we have the option to update the video later, some of the above suggestions could make it even more valuable.

**Comment by slochower** [comment] 2019-04-01 18:08
>Did we want to include the video in the manuscript? 

Size may be an issue. I'm sure I could fiddle with compression, etc. -- but I haven't -- and it's ~70 MB. If anyone has any experience, I'm happy to incorporate suggestions with regards to compression, codec, frame rate, resolution...

> accelerating the typing scenes would help reduce the time and keep viewer attention

I'll see if I can do that. Not sure!

> a voiceover would be helpful to explain what is going on and make sure that the main Manubot features we're highlighting - the fact that anyone can make such a PR, the ease of adding a citation, the automated build, documenting each contribution and review - are obvious

I think this would necessitate working on a script. We could maybe do this today, if we can each work on a few sentences for each part of the video. I think three minutes of speaking might require a few paragraphs, actually. Do you think you'd be up for that?

> (my aside, we could also use text captions to highlight these same features in relevant parts of the video if that is more practical to prepare)

True. Not sure. I don't think audio track is hard, just requires figuring out the best thing to say.

**Comment by agitter** [comment] 2019-04-01 18:14
> We could maybe do this today, if we can each work on a few sentences for each part of the video. I think three minutes of speaking might require a few paragraphs, actually. Do you think you'd be up for that?

Yes, we'd need a script to prepare a 3 min voiceover.  I won't have time today, and actually my entire week is quite full.  I may need to prioritize my time on the other open issues instead of the script.  That's partly what led me to see whether we could host a preliminary version now with text captions and no voice and update it later with a voiceover.

**Comment by slochower** [comment] 2019-04-01 18:21
Updated with longer title slides and faster typing sequences: https://drive.google.com/file/d/1LiMpCdBnvtJDU89yim6DdYHgflzHsro-/view?usp=sharing (72 MB, 2:57)

I will see if I can quickly & easily create text overlays.

**Comment by dhimmel** [comment] 2019-04-01 18:27
> A nice feature of Figshare is that we can version and update it. I don't know how YouTube handles updates.

YouTube only supports a [limited set of updates](https://support.google.com/youtube/answer/57404). Changing the audio doesn't appear to be one of them. Therefore, I'm also leaning towards Figshare to host this video.

Once hosted on Figshare, we could embed it in the manuscript using an iframe, perhaps as a supplemental  video or something. It would look something like:

> ![image](https://user-images.githubusercontent.com/1117703/55350427-153c3c80-548a-11e9-924d-9d088ae4bc55.png)

@slochower or @agitter: do you want to take the lead on the Figshare posting. I think you probably can create a draft post that we can review before publishing it.

We can always also post the video on YouTube later, since that can be helpful for exposure.

**Comment by slochower** [comment] 2019-04-01 22:49
@dhimmel that looks nice!

@agitter did some more fiddling but won't have time again for a little while: https://drive.google.com/open?id=1GDUpdKQVy8D3OSdjh7W8d312qq8bveKH

**Comment by agitter** [comment] 2019-04-03 11:56
The faster pacing and captions help a lot.  Here are some fine-grained suggestions you can take or leave.  Sometime soon we should accept this as a great v1 and move on.
- 0:22 Now that the video is sped up, I think you could skip the cut here and show the entire message being typed
- 0:29 Maybe add an extra second or two to dwell on this titlecard?  `suggestions are requested` sounds better to me if it fits.
- 0:38 The cut here feels fast because the next shot shows the manuscript text briefly and then returns to the meta review to get the URL.
- 0:45 Did this previously show the scroll to the bottom of the page?  I suggest keeping that in given the new accelerated pace.
- 1:29 Should we use a different term besides `URL` in the caption?  The URL is still https://manubot.github.io/try-manubot/  Perhaps `The manuscript is updated` or `The manuscript HTML and PDF are updated`?

@dhimmel sure, let's embed the video and include it as a supplemental video.  Can we automatically number and cross-reference supplemental files?

It's easy for me to post this to figshare.  However, @slochower, you made the video so it may be better for you to take control of it and have it associated with your account.  If you don't use figshare, I'm happy to upload it and share a preview link.

**Comment by slochower** [comment] 2019-04-03 14:12
Tried to incorporate your suggestions @agitter, but may have made minor regression in other areas (still getting the hang of this). I've uploaded to Figshare: https://doi.org/10.6084/m9.figshare.7946192.v1. I think should be okay for version 1. I'm happy to revisit in the future.

**Comment by agitter** [comment] 2019-04-03 20:10
Thanks all of your work on this video.  It's an excellent quick intro to some of Manubot's best features.

**Comment by slochower** [comment] 2019-04-03 20:50
Great :) Feel free to close this issue once we mentioned it in the response to reviewers.

**Comment by dhimmel** [comment] 2019-04-03 20:57
Interesting that the raw video on Figshare is 1920 × 1080 pixels, but the version it plays online is lower resolution.

**Comment by slochower** [comment] 2019-04-03 21:03
Didn't notice that myself. I did export at 1920 x 1080, because I thought that was high enough resolution without being too high. I can re-export at a lower resolution if the inline player shows it differently.

**Comment by dhimmel** [comment] 2019-04-05 15:28
I'll open a PR to add the video to the manuscript.

**Closed as completed** 2019-04-09 02:58 UTC
